name: art_sweetalert_plus
description: "A beautiful, responsive, customizable, accessible replacement, easy use for flutter popup boxes. Both supported ios and android."
version: 0.0.2
homepage: https://github.com/OscarTinajero117/art_sweetalert_plus
repository: https://github.com/OscarTinajero117/art_sweetalert_plus.git
issues: https://github.com/OscarTinajero117/art_sweetalert_plus/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
